@startuml

actor Usuario

participant View
participant Controller
participant Service
participant Repository
database SQLite

Usuario -> View : Solicita consulta de filmes
View -> Controller : consultarFilmes()
Controller -> Service : listarFilmes()
Service -> Repository : buscarFilmes()
Repository -> SQLite : SELECT * FROM filme
SQLite --> Repository : dados dos filmes
Repository --> Service : lista de filmes
Service --> Controller : lista de filmes
Controller --> View : retorna filmes
View --> Usuario : exibe filmes

@enduml